version: '2'
services:
    memegenerator-app:
        image: memegenerator
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://memegenerator-mysql:3306/memegenerator?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    memegenerator-mysql:
        extends:
            file: mysql.yml
            service: memegenerator-mysql
